Master2
DS-jr/telegram-keywords-bot pull request #4
Opened 2022-10-03 08:20 UTC by DS-jr

2022-10-03 08:30 UTC, DS-jr commented
@forthe94 , please, approve before the merge.

2022-10-03 13:33 UTC, forthe94 requested changes

2022-10-03 13:33 UTC, forthe94 commented on readme.md
>    - `pip3 install  pip3 install  tgcrypto`
можно заменить всё на pip install -r requirements.txt

2022-10-03 13:33 UTC, forthe94 commented on bot.py
> -        source = 'в чате {}{} от {}'.format(
Не стоит оставлять лишние комментарии.

2022-10-05 06:19 UTC, DS-jr commented on bot.py
> -        source = 'в чате {}{} от {}'.format(
Ok!

2022-10-05 07:05 UTC, DS-jr commented on readme.md
>    - `pip3 install  pip3 install  tgcrypto`
Updated ReadMe instructions in Master2 branch

2022-10-07 07:52 UTC, merged